import type { WidgetConfig } from "./widget-config";

export interface WidgetPreset {
  id: string;
  name: string;
  description: string;
  suggestedPrimaryColor: string;
  config: WidgetConfig;
}

export const WIDGET_PRESETS: WidgetPreset[] = [
  {
    id: "classic-light",
    name: "Classic Light",
    description: "Clean et professionnel",
    suggestedPrimaryColor: "#1A56DB",
    config: {
      theme: "light",
      presetId: "classic-light",
      headerStyle: "solid",
      headerTextColor: "#FFFFFF",
      backgroundColor: "#F9FAFB",
      backgroundPattern: "none",
      userMessageBgColor: "#1A56DB",
      userMessageTextColor: "#FFFFFF",
      botMessageBgColor: "#FFFFFF",
      botMessageTextColor: "#111827",
      messageBorderRadius: "rounded",
      fontFamily: "inter",
      bubbleIcon: "chat",
      bubbleSize: "md",
      widgetBorderRadius: "rounded",
      widgetShadow: "lg",
      glassEffect: false,
      showBranding: true,
    },
  },
  {
    id: "dark-mode",
    name: "Dark Mode",
    description: "Sombre et moderne",
    suggestedPrimaryColor: "#6366F1",
    config: {
      theme: "dark",
      presetId: "dark-mode",
      headerStyle: "solid",
      headerTextColor: "#F9FAFB",
      backgroundColor: "#1A1A2E",
      backgroundPattern: "none",
      userMessageBgColor: "#6366F1",
      userMessageTextColor: "#FFFFFF",
      botMessageBgColor: "#2D2D44",
      botMessageTextColor: "#E5E7EB",
      messageBorderRadius: "rounded",
      fontFamily: "inter",
      bubbleIcon: "message-circle",
      bubbleSize: "md",
      widgetBorderRadius: "rounded",
      widgetShadow: "md",
      glassEffect: false,
      showBranding: true,
    },
  },
  {
    id: "gradient-sunset",
    name: "Sunset",
    description: "Chaleureux et vibrant",
    suggestedPrimaryColor: "#F97316",
    config: {
      theme: "custom",
      presetId: "gradient-sunset",
      headerStyle: "gradient",
      headerGradientFrom: "#F97316",
      headerGradientTo: "#EC4899",
      headerTextColor: "#FFFFFF",
      backgroundColor: "#FFF7ED",
      backgroundPattern: "none",
      userMessageBgColor: "#F97316",
      userMessageTextColor: "#FFFFFF",
      botMessageBgColor: "#FFFFFF",
      botMessageTextColor: "#1F2937",
      messageBorderRadius: "pill",
      fontFamily: "poppins",
      bubbleIcon: "sparkle",
      bubbleSize: "lg",
      widgetBorderRadius: "pill",
      widgetShadow: "lg",
      glassEffect: false,
      showBranding: true,
    },
  },
  {
    id: "ocean-blue",
    name: "Ocean Blue",
    description: "Frais et professionnel",
    suggestedPrimaryColor: "#0EA5E9",
    config: {
      theme: "custom",
      presetId: "ocean-blue",
      headerStyle: "gradient",
      headerGradientFrom: "#0EA5E9",
      headerGradientTo: "#6366F1",
      headerTextColor: "#FFFFFF",
      backgroundColor: "#F0F9FF",
      backgroundPattern: "dots",
      userMessageBgColor: "#0EA5E9",
      userMessageTextColor: "#FFFFFF",
      botMessageBgColor: "#FFFFFF",
      botMessageTextColor: "#0F172A",
      messageBorderRadius: "rounded",
      fontFamily: "dm-sans",
      bubbleIcon: "chat",
      bubbleSize: "md",
      widgetBorderRadius: "rounded",
      widgetShadow: "lg",
      glassEffect: false,
      showBranding: true,
    },
  },
  {
    id: "minimal",
    name: "Minimal",
    description: "Épuré et discret",
    suggestedPrimaryColor: "#18181B",
    config: {
      theme: "light",
      presetId: "minimal",
      headerStyle: "transparent",
      headerTextColor: "#18181B",
      backgroundColor: "#FFFFFF",
      backgroundPattern: "none",
      userMessageBgColor: "#18181B",
      userMessageTextColor: "#FFFFFF",
      botMessageBgColor: "#F4F4F5",
      botMessageTextColor: "#18181B",
      messageBorderRadius: "sharp",
      fontFamily: "geist",
      bubbleIcon: "message-circle",
      bubbleSize: "sm",
      widgetBorderRadius: "sharp",
      widgetShadow: "sm",
      glassEffect: false,
      showBranding: true,
    },
  },
  {
    id: "glass",
    name: "Glass",
    description: "Glassmorphism élégant",
    suggestedPrimaryColor: "#8B5CF6",
    config: {
      theme: "custom",
      presetId: "glass",
      headerStyle: "gradient",
      headerGradientFrom: "#8B5CF6",
      headerGradientTo: "#06B6D4",
      headerTextColor: "#FFFFFF",
      backgroundColor: "rgba(255,255,255,0.6)",
      backgroundPattern: "none",
      userMessageBgColor: "#8B5CF6",
      userMessageTextColor: "#FFFFFF",
      botMessageBgColor: "rgba(255,255,255,0.7)",
      botMessageTextColor: "#1E293B",
      messageBorderRadius: "pill",
      fontFamily: "inter",
      bubbleIcon: "sparkle",
      bubbleSize: "lg",
      widgetBorderRadius: "pill",
      widgetShadow: "glow",
      glassEffect: true,
      showBranding: true,
    },
  },
];
